routes/user_route.py
import json
from flask import Blueprint, current_app, flash, redirect, render_template, url_for, request, session, jsonify, current_app
from models.user_models.greenhouse_model import get_custom_plant, get_default_plants, get_chosen_plants, new_plant, get_reserved_pins, remove_pin, update_custom_plant, update_custom_sensor, update_watered_plant, user_reserved_pins, get_user_plants, get_plant, update_default_plant, delete_plant, get_water_amount
from models.user_models.user_model import get_user, get_number_of_plants, update_photo, update_user
from arduino import fetch_pins_arduino, set_pin_arduino, get_reserved_pins_arduino, release_pin_arduino, pins_to_read, water_arduino
from services.entity_services import customPlant, newPlant, newReport, normalize_plants
from services.sensor_service import start
from services.weather_service import get_forecast, get_latest_forecast
from services.watering_service import watering_logic, start_watering, stop_watering
import time, threading, schedule
import os

user_route = Blueprint('user_route', __name__)    

@user_route.route("/")
def user_dashboard():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    if "USER_LOGGED_IN" in session:
        user = get_user(user_id)
        raw_plants = get_user_plants(user_id)
        plants = normalize_plants(raw_plants) if raw_plants else []
        return render_template("user_templates/index.html", user = user, plants = plants)
    return redirect(url_for('main.login'))

@user_route.route("/get_coords", methods=["POST"])
def get_coords():
    data = request.get_json()
    lat = data.get("latitude")
    long = data.get("longitude")
    forecast = get_latest_forecast(lat, long)
    return jsonify({'forecast' : forecast})

@user_route.route("/default_plant", methods=["POST", "GET"])
def default_plant():
    default_plants = get_default_plants()
    user_id = session.get("USER_LOGGED_IN")['user_id']
    user = get_user(user_id)
    return render_template("user_templates/add-plant.html", default_plants = default_plants, user = user)

@user_route.route("/greenhouse")
def greenhouse():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    raw_plants = get_user_plants(user_id)
    user = get_user(user_id)
    plants = normalize_plants(raw_plants)
    return render_template("user_templates/greenhouse.html", plants = plants, user = user)

@user_route.route("/watering_mode", methods=["POST"])
def watering_mode():
    user_id = session.get("USER_LOGGED_IN")
    data = request.get_json()
    mode = data.get("mode")
    
    return jsonify({'mode' : mode})

@user_route.route("/automatic_watering", methods=["POST", "GET"])
def automatic_watering():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    start(user_id)
    print("HAHAAHAHHA")
    data = request.get_json()
    longitude = data.get("longitude")
    latitude = data.get("latitude")
    forecast = get_forecast(latitude, longitude)
    start_watering(forecast, user_id)
    return jsonify({"maverick" : "gwapo"})

@user_route.route("/manual_watering", methods=["POST", "GET"])
def manual_watering():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    stop_watering(user_id)
    print("MANUAL MODE")
    data = request.get_json()
    plants = data.get("plants")
    for plant in plants:
        water_amount = get_water_amount(plant['plantId'])        
        #CONVERT ML TO TIME(MILISECONDS)
        PUMP_PER_SECOND = float(25)
        watering_time = (float(water_amount['water_amount']) / PUMP_PER_SECOND) * 1000
        
        water_arduino({plant['sensorPin'] : watering_time})
        update_watered_plant(plant["plantId"], plant["sensorPin"])
    return jsonify({'plant' : plant})

@user_route.route("/add_default_plant", methods=["POST"])
def add_default_plant():
    id = request.form.getlist("plant_checkbox")
    plants = get_chosen_plants(tuple(id))
    user_id = session.get("USER_LOGGED_IN")['user_id']
    user = get_user(user_id)
    if plants:
        reserved_pins = get_reserved_pins()
        return render_template('user_templates/set-pin.html', plants = plants, reserved_pins = reserved_pins, user = user)
    else:
        flash("Select a plant first")
        return redirect(url_for('user_route.default_plant'))
    
@user_route.route("/custom_plant")
def custom_plant():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    user = get_user(user_id)
    return render_template("user_templates/add-custom-plant.html", user = user)

@user_route.route("/add_custom_plant", methods=["POST"])
def add_custom_plant():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    new = customPlant(request.form, user_id)
    user = get_user(user_id)
    insert = new.insert_plant()
    plant = get_custom_plant(insert)
    reserved_pins = get_reserved_pins()
    return render_template('user_templates/custom-plant-pin.html', plant = plant, reserved_pins = reserved_pins, user = user)

@user_route.route("/fetch_pins")
def fetch_pins():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    data = fetch_pins_arduino()
    return jsonify(data)

@user_route.route("/set_pin_process", methods=["POST", "GET"])
def set_pin_process():
    pin = request.form.get("pin")
    plant_id = request.form.get("currentPlant")
    user_id = session.get("USER_LOGGED_IN")['user_id']
    sensor_name = request.form.get("sensorName")
    image = request.files.get("image")
    
    if image:
        filepath = os.path.join(current_app.config["UPLOAD_FOLDER"], image.filename)
        image.save(filepath)
        plant_photo = "plant_images/" + image.filename
    else:
        plant_photo = "plant_images/default_img.jpg"
        
    new_plant(user_id, plant_id, sensor_name, pin, plant_photo)
    set_pin_arduino(pin)
    
    return jsonify({"status" : True})

@user_route.route("/release_pin", methods=["POST"])
def release_pin():
    data = request.get_json()
    pin = data.get("pin")
    plantId = data.get("plantId")
    user_id = session.get("USER_LOGGED_IN")['user_id']
    release_pin_arduino(pin)
    remove_pin(plantId, user_id)
    return jsonify({'status' : 'success'})

@user_route.route("/report_issues")
def report_issues():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    user = get_user(user_id)
    return render_template('user_templates/report-issues.html', user = user)

@user_route.route("/submit_report", methods=["POST"])
def submit_report():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    new_report = newReport(request.form, user_id)
    new_report.add_report()    
    return redirect(url_for('user_route.report_issues'))

@user_route.route("/plant_information/<string:id>")
def plant_information(id):
    plant = get_plant(id)
    return jsonify({'plant' : plant})

@user_route.route("/action/<string:id>", methods=["POST"])
def action(id):
    action = request.form.get("action")
    sensor_pin = request.form.get("select-pin")
    plant_name = request.form.get("custom-plant-name")
    soil_type = request.form.get("soil-type")
    description = request.form.get("description")
    water_amount = request.form.get("optimal-water-amount")
    min_moisture = request.form.get("soil-min-moisture")
    max_moisture = request.form.get("soil-max-moisture")
    min_temp = request.form.get("ideal-min-temp")
    max_temp = request.form.get("ideal-max-temp")
    sensor_pin = request.form.get("select-pin")
    plant_id = get_custom_plant(id)
    file = request.files.get("plant-photo")
    is_default = request.form.get("is-default")
    
    print(description, min_temp, max_temp)
    
    if action == "update":
        if is_default is None:
            update_custom_sensor(id, sensor_pin)
            update_custom_plant(plant_id, plant_name, description, soil_type, water_amount, min_moisture, max_moisture, min_temp, max_temp)
            print("aylabyu")
        else:
            
            if file:
                filepath = os.path.join(current_app.config["UPLOAD_FOLDER"], file.filename)
                file.save(filepath)
                plant_photo = "plant_images/" + file.filename
            else:
                plant_photo = "plant_images/default_img.jpg"
            
            update_default_plant(sensor_pin, id, plant_photo)
            set_pin_arduino(sensor_pin)
    elif action == "delete":
        delete_plant(id)

    return redirect(url_for('user_route.greenhouse'))

@user_route.route("/profile/<string:user_id>")
def profile(user_id):
    user_information = get_user(user_id)
    plants = get_number_of_plants(user_id)
    return render_template('user_templates/profile.html', user = user_information, plants = plants)

@user_route.route("/update_profile_picture/<string:user_id>", methods=["POST", "GET"])
def update_profile_picture(user_id):
    image = request.files.get("image")
    
    if image:
        filepath = os.path.join(current_app.config["UPLOAD_FOLDER"], image.filename)
        image.save(filepath)
        profile_photo = "plant_images/" + image.filename
        update_photo(profile_photo, user_id)
        
    return jsonify({'ako ni' : 'natoy'})

@user_route.route("/edit_profile/<string:user_id>")
def edit_profile(user_id):
    user = get_user(user_id)
    return jsonify({'user' : user})

@user_route.route("/update_profile/<string:user_id>", methods=["POST"])
def update_profile(user_id):
    first_name = request.form.get("first-name-input")
    last_name = request.form.get("last-name-input")
    email = request.form.get("email-input")
    phone_number = request.form.get("phone-number-input")
    birthdate = request.form.get("birthdate-input")
    update_user(first_name, last_name, email, phone_number, birthdate, user_id)
    return redirect(url_for('user_route.profile', user_id = user_id))

@user_route.route("/logout")
def logout():
    user_id = session.get("USER_LOGGED_IN")['user_id']
    stop_watering(user_id)
    session.pop("USER_LOGGED_IN")
    return redirect(url_for('home'))

templates/user_templates/add-custom-plant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <main>

        {% include 'user_templates/components/header.html' %}

        {% include 'user_templates/components/sidebar.html'%}

        <link rel="stylesheet" href="{{url_for('static', filename='css/user/add-custom-plant.css')}}">

        <div class="main-content">
            <a href="{{url_for('user_route.greenhouse')}}">
                <img src="{{url_for('static', filename='assets/icons/back.png')}}" alt="" style="width: 30px; height: auto;">
            </a>

            <h1>Add Plants to your Greenhouse</h1>

            <nav>
                <a href="{{url_for('user_route.default_plant')}}" class="plant-tab">Default Plant</a>
                <a href="{{url_for('user_route.custom_plant')}}" class="plant-tab active">Custom Plant</a>
            </nav>   

            <hr>

            <p>Quickly add common greenhouse plants with pre-set watering automation for Plant Pulse. Defaults require 1 sensor each (e.g., soil moisture).</p>

            <form action="/user/add_custom_plant" method="POST">
                <div class="plant-items">
                    <label for="plant-name-input">Plant Name </label>
                    <p>Give it a unique name for easy tracking</p>
                    <input type="text" name="plant-name-input" id="plant-name-input" placeholder="e.g., Orchid">

                    <label for="soil-type-input">Soil Type</label>
                    <p>Selecting a default will auto-fill watering needs.</p>
                    <input type="text" name="soil-type-input" id="soil-type-input" placeholder="e.g, Gravel">

                    <label for="description">Description</label>
                    <textarea name="description-input" id="description-input"></textarea>
                
                    <label for="water-amount-input">Water Amount Input</label>
                    <input type="number" name="water-amount-input" id="water-amount-input" placeholder="Optimal Water Amount">

                    
                    <div class="moisture-container">
                        <div>
                            <label for="min-moisture-input">Minimum Moisture</label>
                            <input type="number" name="min-moisture-input" id="min-moisture-input" placeholder="Soil Minimum Moisture">
                        </div>

                        <div>
                            <label for="max-moisture-input">Maximum Moisture</label>
                            <input type="number" name="max-moisture-input" id="min-moisture-input" placeholder="Soil Maximum Moisture">
                        </div>
                    </div>

                    <div class="temperature-container">
                        <div>
                            <label for="min-temp-input">Minimum Temperature</label>
                            <input type="number" name="min-temp-input" id="min-temp-input" placeholder="Ideal Minimum Temperature">
                        </div>

                        <div>
                            <label for="max-temp-input">Maximum Temperature</label>
                            <input type="number" name="max-temp-input" id="max-temp-input" placeholder="Ideal Maximum Temperature"> 
                        </div>
                    </div>
                </div>

                <div class="button-container">
                    <button type="submit" class="add-plant">Add Plants</button>
                </div>
            </form>

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <ul class="flashes">
                        {% for category, message in messages %}
                            <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
        </div>

    </main>

<script>
</script>
</body>
</html>

templates/user_templates/add-plant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head> 
<body>

    <main>

        {% include 'user_templates/components/header.html' %}

        {% include 'user_templates/components/sidebar.html' %}

        <link rel="stylesheet" href="{{url_for('static', filename='css/user/add-plant.css')}}">

        <div class="main-content">
            <a href="{{url_for('user_route.greenhouse')}}"> 
                <img src="{{url_for('static', filename='assets/icons/back.png')}}" alt="" style="width: 30px; height: auto;">
            </a>

            <h2>Add Plants to your Greenhouse</h2>

            <nav>
                <a href="{{url_for('user_route.default_plant')}}" class="plant-tab active">Default Plant</a>
                <a href="{{url_for('user_route.custom_plant')}}" class="plant-tab">Custom Plant</a>
            </nav>   

            <hr>

            <p>Welcome to PlantPulse, your automated greenhouse water system. Configure your setup by selecting plants, assigning pins for sensors, and reviewing sensor requirements.</p>

            <form action="/user/add_default_plant" method="POST">
                <div class="plant-items">
                    {% for plant in default_plants %}
                    <div>
                        <input type="checkbox" name="plant_checkbox" id="{{plant.plant_code}}" value="{{plant.id}}" hidden>
                        <label for="{{plant.plant_code}}">
                            <input type="text" name="id-input" value="{{plant.id}}" hidden>
                            <input type="text" name="plant-code-input" value="{{plant.plant_code}}" hidden>

                            <h4>{{plant.plant_name}}</h4>
                            <p>Code : {{plant.plant_code}}</p>
                            <p>{{plant.description}}</p>
                        </label>
                    </div>
                    {% endfor %}
                </div>

                <div class="button-container">
                    <button type="submit">Add Plants</button>
                </div>
            </form>

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <ul class="flashes">
                        {% for category, message in messages %}
                            <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
        </div>

    </main>


</body>
</html>

templates/user_templates/custom-plant-pin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <main>

        {% include 'user_templates/components/header.html' %}

        <link rel="stylesheet" href="{{url_for('static', filename='css/user/set-pin.css')}}">
        <div class="main-content">
            <a href="{{url_for('user_route.greenhouse')}}">
                <img src="{{url_for('static', filename='assets/icons/back.png')}}" alt="" style="width: 30px; height: auto;">
            </a>

            <h1>Set Pins </h1>

            <hr>
            
            <div class="page-content">

                <div class="plant-container">

                    <div class="container-header">
                        <div class="container-title">
                            <h3>{{plant.plant_name}}</h3>
                            <p class="plant-code" value="{{plant.plant_code}}">Code :{{plant.plant_code}}</p>
                            <p>{{plant.description}}</p>
                        </div>
                        <div class="img-container">
                            <img src="" alt="" id="image-preview" style="width: 130px;">
                        </div>
                    </div>
                    
                    <hr>
                    
                    <div class="container-content">
                        <button class="config-btn" data-plant="{{plant.id}}">Configure Pin</button>
                        <input type="file" name="plant-image" id="plant-image" accept="image/*" hidden>
                        <label for="plant-image" class="custom-file-input">Choose Image</label>
                    </div>
                </div>

                <div class="modal">
                    <div class="modal-content">
                        <span class="close">&times;</span>

                        <h2>Set Pin for {{plant.plant_name}}</h2>

                        <hr>

                        <div class="inputs">
                            <div>
                                <label for="select-pin">Select Pin</label>
                                <select name="select-pin" class="select-pin"></select>
                            </div>

                            <div>
                                <label for="sensor-name">Sensor Name</label>
                                <input type="text" name="sensor-name" class="sensor-name" placeholder="e.g., Tomato Sensor">
                            </div>

                            <button class="set-pin-btn">Set Pin</button>
                        </div>
                    </div>      
                </div>
            </div>
        </div>

    </main>

<script>
document.addEventListener("DOMContentLoaded", async () => {

    const modal = document.querySelector(".modal");
    const setPinButton = modal.querySelector(".set-pin-btn");
    const configureButtons = document.querySelectorAll(".config-btn");
    const releasePin = document.querySelectorAll(".release-pin");
    const select = modal.querySelector(".select-pin");
    const plantImage = document.querySelector("#plant-image");
    const imagePreview = document.querySelector("#image-preview");
    const closeButton = document.querySelectorAll(".close");

    let selectedImage = null;
    let currentPlant = null;

    configureButtons.forEach((button) => {
        button.addEventListener('click', () => openModal(button.dataset.plant));
    });

    async function openModal (plantCode) {
        modal.style.display = "block";
        currentPlant = plantCode;
        select.innerHTML = "";

        try {
            const response = await fetch("http://127.0.0.1:5000/user/fetch_pins");
            const data = await response.json();

            data.available_pins.forEach((pin) => {
                const option = document.createElement("option");
                option.value = pin;
                option.textContent = pin;
                select.appendChild(option);
            });

        } catch (Error) {
            console.log(Error);
        }
    };


    setPinButton.addEventListener('click', async () => {
        const pin = select.value;
        const sensorName = document.querySelector(".sensor-name").value;

        const formData = new FormData()
        formData.append("pin", pin)
        formData.append("currentPlant", currentPlant)
        formData.append("sensorName", sensorName)
        formData.append("image", selectedImage)

        try {
            const response = await fetch("http://127.0.0.1:5000/user/set_pin_process", {
                method: "POST",
                body: formData
            });

            const data = await response.json();

            console.log(data);

        } catch (Error) {
            console.log(Error);
        }
    });

    releasePin.forEach((button) => {
        button.addEventListener('click', async () => {
            const pin = button.dataset.pin;
            const plantContainer = button.closest("div");
            const plantId = plantContainer.querySelector(".plant-id").value;
            console.log(plantId)
            try {
                const response = await fetch("http://127.0.0.1:5000/user/release_pin", {
                    method: "POST",
                    headers: {"Content-Type" : "application/json"},
                    body: JSON.stringify({plantId, pin})
                });
                const data = await response.json();

                if (data.status) {
                    button.previousElementSibling.remove();
                    button.remove()
                }

            } catch (Error) {
                console.log(Error);
            }
        });
    });

    plantImage.addEventListener('change', imageChange)

    function imageChange() {
        const image = plantImage.files[0];
        
        if (image) {
            selectedImage = image
            imagePreview.src = URL.createObjectURL(image);
        }
    }

    closeButton.forEach(button => {
        button.addEventListener('click', () => {
            modal.style.display = "none";
        });
    });

});
</script>

</body>
</html>

templates/user_templates/greenhouse-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <a href="{{url_for('user_route.add_custom_plant')}}">
        <button>Add Plant ;></button>
    </a>


    <form action="/user/add_default_plant" method="POST">
        {% for plant in default_plants %}
        <div>
            <input type="checkbox" name="plant_checkbox" id="{{plant.plant_code}}" value="{{plant.id}}">
            <label for="{{plant.plant_code}}">
                <input type="text" name="id-input" value="{{plant.id}}" hidden>
                <input type="text" name="plant-code-input" value="{{plant.plant_code}}" hidden>

                {{plant.plant_code}}
                {{plant.plant_name}}
                {{plant.description}}
                {{plant.soil_type}}
                {{plant.optimal_water_amount}}
                {{plant.soil_min_moisture}} {{plant.soil_max_moisture}}
                {{plant.ideal_min_temp}} {{plant.ideal_max_temp}}
            </label>
        </div>
        {% endfor %}

        <button type="submit">addPlants</button>
    </form>
    


</body>
</html>

templates/user_templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/user/profile.css')}}">
</head>
<body>
    
    <main>

        <header>
            <div id="logo-container">
                <div id="img-container">
                    <img src="{{url_for('static', filename='assets/logos/plant_logo.png')}}" alt="Plant Pulse logo" id="logo">
                </div>
                <span>lant Pulse</span>
            </div>
        </header>

        <div class="main-content">
            <a href="{{url_for('user_route.greenhouse')}}">
                <img src="{{url_for('static', filename='assets/icons/back.png')}}" alt="" style="width: 30px; height: auto;">
            </a>

            <div class="profile-header">
                <div class="image-container">
                    <img src="{{url_for('static', filename=user.profile_photo if user.profile_photo else 'assets/profile.jfif')}}" alt="">
                    <input type="file" name="profile-picture" id="profile-picture" data-user-id="{{user.id}}" hidden>
                    <label for="profile-picture" class="custom-file-input">
                        0
                    </label>
                </div>
                
                <div class="system-status">
                    <h3>System Status: </h3>
                    <h3><span></span>Online</h3>
                    <p>Last update: 2 mins. ago</p> 
                </div>
            </div>

            <div class="profile-content">
                <div class="col-1">
                    <h3>Personal Info</h3>
                    <button class="edit-btn" data-user-id="{{user.id}}">Edit</button>
                </div>

                <div class="col-2">
                    <div>
                        <p class="content-title">Full Name</p>
                        <p>{{user.first_name}} {{user.last_name}}</p>
                    </div>

                    <div>
                        <p class="content-title">Email</p>
                        <p>{{user.email}}</p>
                    </div>

                    <div>
                        <p class="content-title">Phone Number</p>
                        <p>{{user.phone_number}}</p>
                    </div>
                </div>

                <div class="col-3">
                    <div>
                        <p class="content-title">Date of Birth</p>
                        <p>{{user.birthdate}}</p>
                    </div>

                    <div>
                        <p class="content-title">Plants</p>
                        <p>{{plants}}</p>
                    </div>
                </div>


                <div class="button-container">
                    <a href="{{url_for('user_route.logout')}}">
                        <button>LOG OUT</button>
                    </a>
                </div>
            </div>

            <div class="modal">
                <div class="modal-content">

                </div>
            </div>

        </div>

    </main>

<script>

const fileInput = document.querySelector("#profile-picture");
const editButton = document.querySelector(".edit-btn");
const modal = document.querySelector(".modal");
const modalContent = modal.querySelector(".modal-content");
let selectedImage = null;

fileInput.addEventListener('change', async () => {
    const image = fileInput.files[0]
    const userId = fileInput.dataset.userId;

    if (image) {
        selectedImage = image;
    }

    const formData = new FormData();
    formData.append("image", image);

    try {
        const response = await fetch(`http://127.0.0.1:5000/user/update_profile_picture/${userId}`, {
            method: "POST",
            body: formData
        });
        const data = await response.json();
        console.log(data);

        location.reload();
    } catch (Error) {
        console.log(Error);
    }
});

editButton.addEventListener('click', async () => {
    modal.style.visibility = "visible";
    const userId = editButton.dataset.userId;

    try {
        const response = await fetch(`http://127.0.0.1:5000/user/edit_profile/${userId}`)
        const data = await response.json();
        const user = data.user;
        modalContent.innerHTML = renderData(user);
        
        const closeButton = modalContent.querySelector(".close");

        closeButton.addEventListener('click', () => {
            modal.style.visibility = "hidden"
        });

    } catch (Error) {
        console.log(Error);
    }

});

function renderData (user) {

    let formattedDate = "";
    if (user.birthdate) {
        const date = new Date(user.birthdate);
        if (!isNaN(date)) {
            formattedDate = date.toISOString().split("T")[0];
        }
    }

    console.log(user.birthdate);
    return `
        <span class="close">&times;</span>
        <h2>Update Profile</h2>
        <hr>

        <form action="/user/update_profile/${user.id}" method="POST">
            <div class="input-group">
                <div class="info-group">
                    <label for="first-name-input">First Name</label>
                    <input type="text" name="first-name-input" value="${user.first_name}">
                </div>

                <div class="info-group">
                    <label for="last-name-input">Last Name</label>
                    <input type="text" name="last-name-input" value="${user.last_name}">
                </div>

                <div class="info-group">
                    <label for="email-input">Email</label>
                    <input type="email" name="email-input" value="${user.email}">
                </div>

                <div class="info-group">
                    <label for="phone-number-input">Phone Number</label>
                    <input type="text" name="phone-number-input" value="${user.phone_number}">
                </div>

                <div class="info-group">
                    <label for="birthdate-input">Birthdate</label>
                    <input type="date" name="birthdate-input" value="${formattedDate}">
                </div>
            </div>

            <div class="modal-buttons">
                <button name="action" type="submit" value="update" class="update-btn">Update</button>
            </div>
        </form>
    `
}

</script>
</body>
</html>